### ISSUE TITLE
无法开机呀

### ISSUE THREAD

**Issue by Makat0** [acai66/Acai-Oneplus6-or-Oneplus6T-Nethunter-kernel#2]
刷了Magisk-v20.4，然后刷内核，卡在了开机动画，无限重启。。

**Comment by acai66** [comment]
过段时间我再更新一版

**Comment by acai66** [comment]
![Screenshot_20200504-202920__01](https://user-images.githubusercontent.com/37766207/80965953-15093000-8e46-11ea-8ae7-0a79855a9525.jpg)
目前还有点小问题

**Comment by Makat0** [comment]
v6我刷了两次，都是一次是因为没卸载nethunter卸载了term，导致死机无限重启。一次是因为插了usb手机死机导致无限重启。目前在用v9，这版本好像还可以。请问v10更新了哪些内容呀

**Comment by acai66** [comment]
> v6我刷了两次，都是一次是因为没卸载nethunter卸载了term，导致死机无限重启。一次是因为插了usb手机死机导致无限重启。目前在用v9，这版本好像还可以。请问v10更新了哪些内容呀

尝试支持kvm虚拟化，内核中已开启，好像并不能用

**Comment by Makat0** [comment]
加油大哥，我先用v9，目前还没出大问题。就是手中有些网卡没驱起来。

**Comment by acai66** [comment]
> 加油大哥，我先用v9，目前还没出大问题。就是手中有些网卡没驱起来。

什么型号的网卡

**Comment by acai66** [comment]
V10已更新

**Comment by Makat0** [comment]
先收藏，手机东西有点多了，不敢刷。。

**Comment by Droid-MAX** [comment]
要刷其他内核，是不是得把magisk里的那个AnyKernel3 Helper Module先给删掉再重启一下，再重启到twrp刷其他内核？

**Comment by acai66** [comment]
> 要刷其他内核，是不是得把magisk里的那个AnyKernel3 Helper Module先给删掉再重启一下，再重启到twrp刷其他内核？

不需要，那个模块会自动处理的。换其它内核的话，内核版本发生变化后就自动被删了，升级内核的话，那个模块也会跟着重新安装的
