### ISSUE TITLE
HID interface not found

### ISSUE THREAD

**Issue by Yogesh111264** [acai66/Acai-Oneplus6-or-Oneplus6T-Nethunter-kernel#3]
HID interface not found.
![Screenshot_20200520-053446](https://user-images.githubusercontent.com/65632559/82390202-bb1a8400-9a5b-11ea-8dbf-b9393f6dbca3.jpg)

**Comment by acai66** [comment]
V10 updated, you can change usb mode in NetHunter app -> USB Arsenal -> USB Function

**Comment by Yogesh111264** [comment]
Kindly share link of V10 only V6 available here.

**Comment by acai66** [comment]
In GitHub releases

**Comment by Yogesh111264** [comment]
V10 is not in release folder. 
![Screenshot_20200522-230218](https://user-images.githubusercontent.com/65632559/82694142-5ab85c00-9c80-11ea-86c5-b78db36ce9a7.jpg)

**Comment by acai66** [comment]
[release page](https://github.com/acai66/Acai-Oneplus6-or-Oneplus6T-Nethunter-Kernel/releases)

**Comment by Yogesh111264** [comment]
Thanks buddy.
