### ISSUE TITLE
atheros ar9271 not detected by Kernal

### ISSUE THREAD

**Issue by Yogesh111264** [acai66/Acai-Oneplus6-or-Oneplus6T-Nethunter-kernel#4]
![Screenshot_20200525-140234](https://user-images.githubusercontent.com/65632559/82794706-8dd13a00-9e90-11ea-8f3b-f771accc318b.jpg)
I have attached atheros ar9271 to nethunter. Currently V10 kernal is installed. Adapter not being detected in airmon-ng even LED of adapter not blinking. Does v10 have driver installed for this chipset?

**Comment by acai66** [comment]
you load ath9k_htc drivers faild

**Comment by acai66** [comment]
![Screenshot_20200525-164146](https://user-images.githubusercontent.com/37766207/82795485-ab110300-9ea6-11ea-8ca7-cc088646eec6.jpg)

**Comment by acai66** [comment]
you can try mount /system/lib/modules to your chroot path/lib/modules
`busybox mount -r -o bind /system/lib/modules /path/to/your/chrootpath/lib/modules`

**Comment by Yogesh111264** [comment]
> you can try mount /system/lib/modules to your chroot path/lib/modules
> `busybox mount -r -o bind /system/lib/modules /path/to/your/chrootpath/lib/modules`

Issue resolved. Thanks once again for prompt response. Issues can be marked closed.

![Screenshot_20200525-175522](https://user-images.githubusercontent.com/65632559/82812647-1790ff80-9eb1-11ea-8d4e-700c9e5dd129.jpg)
