### ISSUE TITLE
nethunter系统中找不到/system/lib/modules文件夹，无法加载驱动

### ISSUE THREAD

**Issue by dhdgves** [acai66/Acai-Oneplus6-or-Oneplus6T-Nethunter-kernel#6]
V10内核，一加六氧10.3.5
# modprobe 88XXau

modprobe: FATAL: Module 88XXau not found in directory /lib/modules/4.9.222-Acai-Nethunter-V10-HenTaiKernel-CI

# depmod
 depmod: ERROR: could not open directory /lib/modules/4.9.222-Acai-Nethunter-V10-HenTaiKernel-CI: No such file or directory
depmod: FATAL: could not search modules: No such file or directory

进入/system/lib,找不到modulea文件夹(kali nethunter),但是在termux(非nethunter)中可以找到。

**Comment by acai66** [comment]
> V10内核，一加六氧10.3.5
> 
> # modprobe 88XXau
> modprobe: FATAL: Module 88XXau not found in directory /lib/modules/4.9.222-Acai-Nethunter-V10-HenTaiKernel-CI
> 
> # depmod
> depmod: ERROR: could not open directory /lib/modules/4.9.222-Acai-Nethunter-V10-HenTaiKernel-CI: No such file or directory
> depmod: FATAL: could not search modules: No such file or directory
> 
> 进入/system/lib,找不到modulea文件夹(kali nethunter),但是在termux(非nethunter)中可以找到。

新版nethunter启动脚本不包含挂载libs/modules了，可以手动挂载

**Comment by acai66** [comment]
这个命令供参考，其中路径可能要做些修改，
在安卓终端环境执行，不是kali
```
su -c "/data/data/com.offsec.nethunter/files/scripts/bin/busybox_nh mount /system/lib/modules/ /data/local/nhsystem/kalifs/lib/modules"
```

**Comment by dhdgves** [comment]
在本地终端执行完毕之后，发现没有任何变化。在kali中，仍然没有出现/system/lib/modules
,尝试重启kali chroot，但是依旧无变化.

**Comment by acai66** [comment]
不在/system下，挂载到nethunter的lib/modules

**Comment by dhdgves** [comment]
这里也检查过了，的确没有任何变化。一下是执行上述命令(执行成功，无报错)后，kali中情况
root@kali:/lib/modules# ls
root@kali:/lib/modules# ls -al
total 16
drwxr-xr-x.  2 root root 4096 May  4 14:43 .
drwxr-xr-x. 90 root root 4096 Aug 19 14:43 ..
root@kali:/lib/modules# depmod
depmod: ERROR: could not open directory /lib/modules/4.9.222-Acai-Nethunter-V10-HenTaiKernel-CI: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
root@kali:/lib/modules# modprobe 88XXau
modprobe: FATAL: Module 88XXau not found in directory /lib/modules/4.9.222-Acai-Nethunter-V10-HenTaiKernel-CI

**Comment by acai66** [comment]
> 这里也检查过了，的确没有任何变化。一下是执行上述命令(执行成功，无报错)后，kali中情况
> root@kali:/lib/modules# ls
> root@kali:/lib/modules# ls -al
> total 16
> drwxr-xr-x. 2 root root 4096 May 4 14:43 .
> drwxr-xr-x. 90 root root 4096 Aug 19 14:43 ..
> root@kali:/lib/modules# depmod
> depmod: ERROR: could not open directory /lib/modules/4.9.222-Acai-Nethunter-V10-HenTaiKernel-CI: No such file or directory
> depmod: FATAL: could not search modules: No such file or directory
> root@kali:/lib/modules# modprobe 88XXau
> modprobe: FATAL: Module 88XXau not found in directory /lib/modules/4.9.222-Acai-Nethunter-V10-HenTaiKernel-CI

![Screenshot_20200819-234719](https://user-images.githubusercontent.com/37766207/90658613-5e0ab600-e276-11ea-82f5-bee6ae8b4ead.jpg)
检查路径是否有误，挂载成功后是可以在kali中看到的

**Comment by dhdgves** [comment]
解决了，虽然没挂载上，但我寻思复制过去也差不多，多谢指导。
